# Generated by Django 5.2.7 on 2025-11-16 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_remove_availability_bookings_av_listing_076911_idx_and_more'),
        ('listings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('item', 'Item Review'), ('owner', 'Owner Review'), ('renter', 'Renter Review')], help_text='Type of review', max_length=10)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=200)),
                ('comment', models.TextField(help_text='Review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Is review visible to others?')),
                ('booking', models.ForeignKey(blank=True, help_text='Booking this review is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('listing', models.ForeignKey(blank=True, help_text='Item being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('reviewee', models.ForeignKey(blank=True, help_text='User being reviewed (for owner/renter reviews)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_type', 'listing'], name='reviews_rev_review__c68050_idx'), models.Index(fields=['reviewer', 'reviewee'], name='reviews_rev_reviewe_effb55_idx'), models.Index(fields=['booking'], name='reviews_rev_booking_3929ad_idx')],
                'unique_together': {('reviewer', 'booking', 'review_type')},
            },
        ),
    ]
