# Generated by Django 5.2.7 on 2025-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
