# Generated by Django 5.2.7 on 2025-11-16 19:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Item title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Tools', 'Tools'), ('Outdoor', 'Outdoor'), ('Sports', 'Sports'), ('Events', 'Events'), ('Vehicles', 'Vehicles'), ('Home & Garden', 'Home & Garden'), ('Photography', 'Photography'), ('Music', 'Music'), ('Other', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Acceptable', 'Acceptable')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Rental price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_period', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='day', help_text='Price period (hour, day, week, month)', max_length=10)),
                ('location', models.CharField(help_text='Item location', max_length=255)),
                ('available_from', models.DateField(help_text='Date from which item is available')),
                ('available_to', models.DateField(help_text='Date until which item is available')),
                ('is_available', models.BooleanField(default=True, help_text='Is item currently available for rent?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(help_text='User who owns this item', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'is_available'], name='listings_li_categor_c39bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner', 'is_available'], name='listings_li_owner_i_50719f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['available_from', 'available_to'], name='listings_li_availab_32b643_idx'),
        ),
    ]
