# Generated by Django 5.2.7 on 2025-11-16 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_remove_availability_bookings_av_listing_076911_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='Currency code', max_length=3)),
                ('payment_method', models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CARD', help_text='Payment method used', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Payment status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID from payment gateway', max_length=255, null=True)),
                ('payment_reference', models.CharField(help_text='Internal payment reference', max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('booking', models.OneToOneField(help_text='Booking this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
                ('payer', models.ForeignKey(help_text='User making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', 'status'], name='payments_pa_payer_i_ebdbf4_idx'), models.Index(fields=['recipient', 'status'], name='payments_pa_recipie_8f9c72_idx'), models.Index(fields=['booking'], name='payments_pa_booking_8fd3de_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'), models.Index(fields=['payment_reference'], name='payments_pa_payment_87c4c1_idx')],
            },
        ),
    ]
