# Generated by Django 5.2.8 on 2025-11-09 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(help_text='Temporary field - will be replaced with ForeignKey to Listing model')),
                ('start_date', models.DateField(help_text='Rental start date')),
                ('end_date', models.DateField(help_text='Rental end date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the booking', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total rental price for the period', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from renter', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(help_text='User who is renting the item', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(help_text='Temporary field - will be replaced with ForeignKey to Listing model')),
                ('start_date', models.DateField(help_text='Start of unavailable period')),
                ('end_date', models.DateField(help_text='End of unavailable period')),
                ('reason', models.CharField(blank=True, help_text='Reason for unavailability (e.g., "Booked", "Maintenance")', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Booking that blocks this period (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='bookings.booking')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing_id', 'start_date', 'end_date'], name='bookings_bo_listing_437bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['renter', 'status'], name='bookings_bo_renter__03bef2_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['listing_id', 'start_date', 'end_date'], name='bookings_av_listing_076911_idx'),
        ),
    ]
