# Generated by Django 5.2.7 on 2025-11-16 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('listings', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='availability',
            name='bookings_av_listing_076911_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_listing_437bd0_idx',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='availability',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Listing this availability block is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Item being rented', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['listing', 'start_date', 'end_date'], name='bookings_av_listing_076911_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'start_date', 'end_date'], name='bookings_bo_listing_437bd0_idx'),
        ),
    ]
